### ISSUE TITLE
URL safe base64

### ISSUE THREAD

**Issue by Puyodead1** [GetWVKeys/getwvkeys#19]
PSSHs encoded with url safe base64 are not properly decoded

**Comment by astravaganza** [comment]
Can you provide an example where there's not an expected output?

This works fine for me:
```py
import base64
SAMPLE_PSSH = "AAAAp3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAIcSEFF0U4YtQlb9i61PWEIgBNcSEPCTfpp3yFXwptQ4ZMXZ82USEE1LDKJawVjwucGYPFF+4rUSEJAqBRprNlaurBkm/A9dkjISECZHD0KW1F0Eqbq7RC4WmAAaDXdpZGV2aW5lX3Rlc3QiFnNoYWthX2NlYzViZmY1ZGM0MGRkYzlI49yVmwY="
RAW_DATA = base64.b64decode(SAMPLE_PSSH)
BAD_PSSH = base64.urlsafe_b64encode(RAW_DATA)
assert base64.urlsafe_b64decode(BAD_PSSH) == RAW_DATA
```

**Comment by Puyodead1** [comment]
> Can you provide an example where there's not an expected output?
> 
> Using urlsafe_b64decode works fine for me:
> 
> ```python
> import base64
> SAMPLE_PSSH = "AAAAp3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAIcSEFF0U4YtQlb9i61PWEIgBNcSEPCTfpp3yFXwptQ4ZMXZ82USEE1LDKJawVjwucGYPFF+4rUSEJAqBRprNlaurBkm/A9dkjISECZHD0KW1F0Eqbq7RC4WmAAaDXdpZGV2aW5lX3Rlc3QiFnNoYWthX2NlYzViZmY1ZGM0MGRkYzlI49yVmwY="
> RAW_DATA = base64.b64decode(SAMPLE_PSSH)
> BAD_PSSH = base64.urlsafe_b64encode(RAW_DATA)
> assert base64.urlsafe_b64decode(BAD_PSSH) == RAW_DATA
> ```

on the backend server, if you try using `AAAAp3Bzc2gAAAAA7e-LqXnWSs6jyCfc1R0h7QAAAIcSEFF0U4YtQlb9i61PWEIgBNcSEPCTfpp3yFXwptQ4ZMXZ82USEE1LDKJawVjwucGYPFF-4rUSEJAqBRprNlaurBkm_A9dkjISECZHD0KW1F0Eqbq7RC4WmAAaDXdpZGV2aW5lX3Rlc3QiFnNoYWthX2NlYzViZmY1ZGM0MGRkYzlI49yVmwY=` as the pssh on getwvkeys.cc it will fail
