### ISSUE TITLE
Kid:key format

### ISSUE THREAD

**Issue by mohan585** [GetWVKeys/getwvkeys#23]
in staging for chrome build info of pywidevine endpoint i can't getting kid:key format for key response. it diffcult to find which kid for which key. change the key response json like kid:key

**Comment by Puyodead1** [comment]
> in staging for chrome build info of pywidevine endpoint i can't getting kid:key format for key response. it diffcult to find which kid for which key. change the key response json like kid:key

Staging is based on the production version, and nothing was changed in regards to how key and key ids are returned.

https://github.com/GetWVKeys/getwvkeys/blob/staging/getwvkeys/libraries.py#L454
https://github.com/GetWVKeys/getwvkeys/blob/4cfc6ed42c3ff09fa0c496c2e88b33322ce875fa/getwvkeys/libraries.py#L330

This issue is with whatever script you are using.

**Comment by mohan585** [comment]
the above cached_keys function returning the json data for key response in Keys only and not in kid:key format

https://github.com/GetWVKeys/getwvkeys/blob/4cfc6ed42c3ff09fa0c496c2e88b33322ce875fa/getwvkeys/libraries.py#L224

https://github.com/GetWVKeys/getwvkeys/blob/4cfc6ed42c3ff09fa0c496c2e88b33322ce875fa/getwvkeys/libraries.py#L335

https://github.com/GetWVKeys/getwvkeys/blob/4cfc6ed42c3ff09fa0c496c2e88b33322ce875fa/getwvkeys/libraries.py#L339

**Comment by Puyodead1** [comment]
> the above cached_keys function returning the json data for key response in Keys only and not in kid:key format
> 
> https://github.com/GetWVKeys/getwvkeys/blob/4cfc6ed42c3ff09fa0c496c2e88b33322ce875fa/getwvkeys/libraries.py#L224
> 
> https://github.com/GetWVKeys/getwvkeys/blob/4cfc6ed42c3ff09fa0c496c2e88b33322ce875fa/getwvkeys/libraries.py#L335
> 
> https://github.com/GetWVKeys/getwvkeys/blob/4cfc6ed42c3ff09fa0c496c2e88b33322ce875fa/getwvkeys/libraries.py#L339

again, it works fine. `key` is in the format of `kid:key`

https://github.com/GetWVKeys/getwvkeys/blob/4cfc6ed42c3ff09fa0c496c2e88b33322ce875fa/getwvkeys/libraries.py#L332

https://github.com/GetWVKeys/getwvkeys/blob/4cfc6ed42c3ff09fa0c496c2e88b33322ce875fa/getwvkeys/libraries.py#L460

so `results["keys"].append(key.key)` is literally appending the full key as `kid:key`
As I already said, this is not a problem with GetWVKeys, it's an issue with your script.

**Comment by Puyodead1** [comment]
and for further proof, here is the test curl command on staging
![img](https://i.imgur.com/lJoCbvZ.png)

**Comment by ElCap13** [comment]
i can replicate the issue using the getwvkeys.py template script from the scripts page.
the only thing different between commands is using the chromecdm buildinfo

not using chrome buildinfo:
![image](https://user-images.githubusercontent.com/102562838/199703185-4f2df437-f20d-4dec-8d9d-642cc2e4ef93.png)

using chrome buildinfo:
![image](https://user-images.githubusercontent.com/102562838/199703261-1410323d-d7d3-4b44-9415-6ccfdd929305.png)

using chrome buildinfo verbose:
![image](https://user-images.githubusercontent.com/102562838/199702937-b8d074d1-9daa-433e-be35-9b37c21ab186.png)

**Comment by Puyodead1** [comment]
> i can replicate the issue using the getwvkeys.py template script from the scripts page. the only thing different between commands is using the chromecdm buildinfo
> 
> not using chrome buildinfo: ![image](https://user-images.githubusercontent.com/102562838/199703185-4f2df437-f20d-4dec-8d9d-642cc2e4ef93.png)
> 
> using chrome buildinfo: ![image](https://user-images.githubusercontent.com/102562838/199703261-1410323d-d7d3-4b44-9415-6ccfdd929305.png)
> 
> using chrome buildinfo verbose: ![image](https://user-images.githubusercontent.com/102562838/199702937-b8d074d1-9daa-433e-be35-9b37c21ab186.png)

I really need to start reading better, I completely missed the fact this was about chrome CDM. I'm sorry to both of you for my incompetence. I pushed a fix with e2ad7d4c75993d2000fe2fc91733d0f2e0d843ba
